{
 "title": "FitFlux",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Bio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Breathing Rate",
     "type": "timeseries",
     "description": "Resting HR",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Breathing Rate",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Daily Respiratory Rate Summary",
       "select": [
        [
         { "params": [ "daily_respiratory_rate" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HRV",
     "type": "timeseries",
     "description": "Resting HR",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "DailyRmssd",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Daily Heart Rate Variability Summary",
       "select": [
        [
         { "params": [ "rmssd" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Spo2 ( Avg )",
     "type": "timeseries",
     "description": "Resting HR",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "SpO2",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "oxygen_saturation",
       "select": [
        [
         { "params": [ "oxygen saturation percentage" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "VO2Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 1, "y": 17 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "demographic_vo2max",
       "select": [
        [
         { "params": [ "demographic vo2max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Sleep",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sleep",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "alias": "Deep",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Sleep Summary",
       "query": "SELECT mean(\"minutesDeep\") FROM \"Sleep Summary\" WHERE $timeFilter GROUP BY time(1d) fill(null) ",
       "select": [
        [
         { "params": [ "minutesDeep" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "Light",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Sleep Summary",
       "query": "SELECT mean(\"minutesLight\") FROM \"Sleep Summary\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
       "select": [
        [
         { "params": [ "minutesLight" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "REM",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Sleep Summary",
       "query": "SELECT mean(\"minutesREM\") FROM \"Sleep Summary\" WHERE $timeFilter GROUP BY time(1d) fill(null) ",
       "select": [
        [
         { "params": [ "minutesREM" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "Awake",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Sleep Summary",
       "query": "SELECT mean(\"minutesAwake\") FROM \"Sleep Summary\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
       "select": [
        [
         { "params": [ "minutesAwake" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    },
    {
     "title": "Sleep Efficiency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "Efficiency",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Sleep Summary",
       "query": "SELECT mean(\"efficiency\") FROM \"Sleep Summary\" WHERE $timeFilter GROUP BY time(1d) fill(null) ",
       "select": [
        [
         { "params": [ "efficiency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    },
    {
     "title": "Sleep Regularity",
     "type": "marcusolsson-hourly-heatmap-panel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "alias": "Sleep Regularity",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" }
       ],
       "measurement": "Sleep Levels",
       "query": "SELECT median(\"level\") FROM \"Sleep Levels\" WHERE $timeFilter GROUP BY time(1h) ",
       "select": [
        [
         { "params": [ "level" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    }
   ]
  },
  {
   "title": "Heart",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heart Rate Distribution",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Heart rate histogram",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "HeartRate_Intraday",
       "query": "select mean_value from (SELECT mean(\"beats per minute\") as mean_value FROM \"heart_rate\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value <= 96",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Heart rate histogram > 96",
       "measurement": "HeartRate_Intraday",
       "query": "select mean_value from (SELECT mean(\"beats per minute\") as mean_value FROM \"heart_rate\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value > 96",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Heart rate histogram < 60",
       "measurement": "HeartRate_Intraday",
       "query": "select mean_value from (SELECT mean(\"beats per minute\") as mean_value FROM \"heart_rate\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value < 60",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Heart rate histogram > 110",
       "measurement": "HeartRate_Intraday",
       "query": "select mean_value from (SELECT mean(\"beats per minute\") as mean_value FROM \"heart_rate\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value > 110",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Resting HR",
     "type": "timeseries",
     "description": "Resting HR",
     "gridPos": { "h": 8, "w": 12, "x": 5, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Resting HR",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "daily_resting_heart_rate",
       "select": [
        [
         { "params": [ "beats per minute" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Heart Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Heart rate",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "heart_rate",
       "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"HeartRate_Intraday\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "beats per minute" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Activity over given duration",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 6, "x": 11, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "Light Activity",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Activity Minutes",
       "query": "SELECT mean(\"light\") FROM \"active_minutes\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
       "select": [
        [
         { "params": [ "minutesLightlyActive" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "Intense Activity",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "active_minutes",
       "select": [
        [
         { "params": [ "very" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Fair Activity",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "active_minutes",
       "select": [
        [
         { "params": [ "moderate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Sedentary",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "active_minutes",
       "select": [
        [
         { "params": [ "minutesSedentary" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Avg Activity over given duration",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 6, "x": 10, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "level::tag" ], "type": "tag" }
       ],
       "measurement": "activity_level",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Hourly walk heatmap",
     "type": "marcusolsson-hourly-heatmap-panel",
     "gridPos": { "h": 10, "w": 6, "x": 11, "y": 16 },
     "targets": [
      {
       "alias": "Hourly walk heatmap",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "Steps_Intraday",
       "query": "SELECT sum(\"steps\") FROM \"steps\" WHERE $timeFilter GROUP BY time(1h) fill(0) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    },
    {
     "title": "Activity",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "active_minutes",
       "select": [
        [
         { "params": [ "*" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Activity",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "level::tag" ], "type": "tag" }
       ],
       "measurement": "activity_level",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Intraday Steps",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Intraday Steps",
       "groupBy": [
        { "params": [ "10m" ], "type": "time" }
       ],
       "measurement": "steps",
       "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"HeartRate_Intraday\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "steps" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Steps",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 1, "y": 49 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1d" ], "type": "time" }
       ],
       "measurement": "steps",
       "query": "SELECT sum(\"value\") FROM \"Steps\" WHERE $timeFilter GROUP BY time(1d, ) fill(null)",
       "select": [
        [
         { "params": [ "steps" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Calories",
     "type": "barchart",
     "gridPos": { "h": 14, "w": 17, "x": 1, "y": 57 },
     "targets": [
      {
       "alias": "Calories",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "calories",
       "select": [
        [
         { "params": [ "calories" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Floors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 1, "y": 71 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "floors",
       "select": [
        [
         { "params": [ "floors" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Altitude gain (in meters)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 1, "y": 79 },
     "targets": [
      { "expression": "$A/1000", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Band wearing ",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "HeartRate_Intraday",
     "query": "SELECT last(\"beats per minute\") FROM \"heart_rate\" WHERE $timeFilter GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Data sources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "query": "show tag values with key = \"Device\"   "
    }
   ]
  }
 ]
}